
# Part 6

# Merging

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
temp_data = {'customer':['X','Z','Y','Z','X','X'],'product_code': np.arange(6)} # first create a dictionary
temp_data

{'customer': ['X', 'Z', 'Y', 'Z', 'X', 'X'],
 'product_code': array([0, 1, 2, 3, 4, 5])}

In [3]:
dframe1 = DataFrame(temp_data) # then create a data frame using the data in this dictionary
dframe1

customer  product_code
0        X             0
1        Z             1
2        Y             2
3        Z             3
4        X             4
5        X             5

In [4]:
dframe2 = DataFrame({'customer':['Q','Y','Z'],'state':['TN','KA','MH']}) # create the DF from a dict in one step
dframe2

customer state
0        Q    TN
1        Y    KA
2        Z    MH

In [8]:
pd.merge(dframe1,dframe2, left_on = 'customer', right_on = 'customer') # inner join; R:merge(x=...,y=...,by=...) or dplyr::inner_join(x,y)

customer  product_code state
0        Z             1    MH
1        Z             3    MH
2        Y             2    KA

In [9]:
my_merged_dframe = pd.merge(dframe1,dframe2,left_on = 'customer', right_on = 'customer') # explicitly specify which column to merge by

In [10]:
my_merged_dframe

customer  product_code state
0        Z             1    MH
1        Z             3    MH
2        Y             2    KA

In [11]:
pd.merge(dframe1,dframe2,on = 'customer',how = 'left') # left join

customer  product_code state
0        X             0   NaN
1        Z             1    MH
2        Y             2    KA
3        Z             3    MH
4        X             4   NaN
5        X             5   NaN

In [12]:
pd.merge(dframe1,dframe2,on='customer',how = 'right') # right join

customer  product_code state
0        Z           1.0    MH
1        Z           3.0    MH
2        Y           2.0    KA
3        Q           NaN    TN

In [13]:
pd.merge(dframe1,dframe2,on='customer',how = 'outer') # outer join

customer  product_code state
0        X           0.0   NaN
1        X           4.0   NaN
2        X           5.0   NaN
3        Z           1.0    MH
4        Z           3.0    MH
5        Y           2.0    KA
6        Q           NaN    TN

### Many-to-many merge

In [14]:
dframe3 = DataFrame({'key': ['X', 'X', 'X', 'Y', 'Z', 'Z'],'data_set_3': range(6)})
dframe3

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [15]:
dframe4 = DataFrame({'key': ['Y', 'Y', 'X', 'X', 'Z'],'data_set_4': range(5)})
dframe4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [16]:
pd.merge(dframe3,dframe4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [17]:
# Merging with multiple keys
df_left = DataFrame({'key1': ['SF', 'SF', 'LA'],'key2': ['one', 'two', 'one'],'left_data': [10,20,30]})
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [18]:
df_right = DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],'key2': ['one', 'one', 'one', 'two'],'right_data': [40,50,60,70]})
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [19]:
pd.merge(df_left,df_right,how = 'inner')

key1 key2  left_data  right_data
0   SF  one         10          40
1   SF  one         10          50
2   LA  one         30          60

In [20]:
pd.merge(df_left, df_right, on=['key1', 'key2'], how = 'inner')

key1 key2  left_data  right_data
0   SF  one         10          40
1   SF  one         10          50
2   LA  one         30          60

In [21]:
pd.merge(df_left,df_right,on = 'key1') # merging on a single key when there is more than common column

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

Automatically renames the columns to identify which is from which df, by adding suffixes _x and _y; 

<i>Or we can specify the suffices we want:</i>

In [22]:
pd.merge(df_left,df_right,on = 'key1',suffixes=['_left','_right'])

key1 key2_left  left_data key2_right  right_data
0   SF       one         10        one          40
1   SF       one         10        one          50
2   SF       two         20        one          40
3   SF       two         20        one          50
4   LA       one         30        one          60
5   LA       one         30        two          70

# Merge on index

In [23]:
df_left = DataFrame({'key': ['X','Y','Z','X','Y'],'data': range(5)})
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [24]:
df_right = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])
df_right

group_data
X          10
Y          20

In [25]:
pd.merge(df_left,df_right,left_on = 'key',right_index = True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [26]:
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_left_hr

data_set key1  key2
0       0.0   SF    10
1       1.0   SF    20
2       2.0   SF    30
3       3.0   LA    20
4       4.0   LA    30

In [30]:
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],[20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [31]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

data_set key1  key2  col_1  col_2
0       0.0   SF    10      4      5
0       0.0   SF    10      6      7
1       1.0   SF    20      8      9
3       3.0   LA    20      0      1

Alternative to merge - join

In [29]:
df_left.join(df_right)

data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

In [32]:
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [ ]:
df_right

In [ ]:
dframe1

In [ ]:
dframe2

<a name="concatenate"></a>
# Concatenate

In [33]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr2 = (np.arange(9) + 9).reshape((3,3))
arr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

### Concatenate with <i>numpy</i>

In [35]:
np.concatenate([arr1,arr2],axis=1) # similar to R:cbind

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [36]:
np.concatenate([arr1,arr2],axis=0) # similar to R:rbind

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

### Concatenate with <i>pandas</i>

In [37]:
ser1 =  Series([0,1,2],index=['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [38]:
ser2 = Series([3,4],index=['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [39]:
pd.concat([ser1,ser2]) # default is by row (axis = 0) - result is a series

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [40]:
pd.concat([ser1,ser2],axis=1) # by column (axis = 1) - result is a data frame

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [41]:
pd.concat([ser1,ser2],keys = ['cat1','cat2']) # creates an additional (hierarchical) index

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [42]:
pd.concat([ser1,ser2],keys=['cat1','cat2'],axis = 1) # if we concatenate by column, the keys become column names

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

### Works the same way for data frames

In [43]:
from numpy.random import randn # if I don't do this, I can still use function randn by calling np.random.randn

In [44]:
dframe1 = DataFrame(randn(4,3), columns=['X', 'Y', 'Z'])
dframe1

X         Y         Z
0  2.040587  0.293902  1.581005
1  1.495358  0.179171  0.503788
2 -0.059655 -1.263747 -1.599024
3 -0.332712 -0.373135 -0.975478

In [45]:
dframe2 = DataFrame(randn(3, 3), columns=['Y', 'Q', 'X'])
dframe2

Y         Q         X
0 -0.566628  1.733644  0.396353
1  0.540905  0.809348 -0.782278
2  0.268566  1.376580 -2.219010

In [46]:
pd.concat([dframe1,dframe2]) # preserves the original indices

Q         X         Y         Z
0       NaN  2.040587  0.293902  1.581005
1       NaN  1.495358  0.179171  0.503788
2       NaN -0.059655 -1.263747 -1.599024
3       NaN -0.332712 -0.373135 -0.975478
0  1.733644  0.396353 -0.566628       NaN
1  0.809348 -0.782278  0.540905       NaN
2  1.376580 -2.219010  0.268566       NaN

In [47]:
pd.concat([dframe1,dframe2],ignore_index = True) # ignores original index and creates new (continuous) index

Q         X         Y         Z
0       NaN  2.040587  0.293902  1.581005
1       NaN  1.495358  0.179171  0.503788
2       NaN -0.059655 -1.263747 -1.599024
3       NaN -0.332712 -0.373135 -0.975478
4  1.733644  0.396353 -0.566628       NaN
5  0.809348 -0.782278  0.540905       NaN
6  1.376580 -2.219010  0.268566       NaN

In [48]:
pd.concat([dframe1,dframe2],axis = 1)

X         Y         Z         Y         Q         X
0  2.040587  0.293902  1.581005 -0.566628  1.733644  0.396353
1  1.495358  0.179171  0.503788  0.540905  0.809348 -0.782278
2 -0.059655 -1.263747 -1.599024  0.268566  1.376580 -2.219010
3 -0.332712 -0.373135 -0.975478       NaN       NaN       NaN

## End of part 6