# Part 3


## NumPy

In [2]:
import numpy as np # import numpy and give it the short form ('nickname') np

<b>From Wikipedia:
    
NumPy (pronounced /ˈnʌmpaɪ/ (NUM-py) or sometimes /ˈnʌmpi/ (NUM-pee)) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.</b>

<a href = "https://en.wikipedia.org/wiki/NumPy">Full article here</a>

Some important **Numpy** features:
<ul>
<li>ndarray: fast and space-efficient multidimensional array with vectorized arithmetic and sophisticated broadcasting</li>
<li>Standard vectorized math</li>
<li>Reading / writing arrays to disk</li>
<li>Memory-mapped file access</li>
<li>Linear algebra, rng, fourier transform</li>
<li>Integration of C, C++, FORTRAN</li>
</ul>

**Creating NumPy arrays**

The function *array()* is commonly used to create numpy ndarrays on the fly from other Python sequence-like objects such as tuples and lists.

In [3]:
np.array(range(3))

array([0, 1, 2])

In [4]:
np.array((1, 2, 3)) # from a tuple

array([1, 2, 3])

In [5]:
np.array([1, 2, 3]) # from a list

array([1, 2, 3])

Nested lists result in mutlidimensional arrays:

In [6]:
import random
nestedList = [[random.uniform(0, 9) for x in range(3)] for y in range(4)]
nestedList

[[6.805433500713564, 0.9032582472508374, 1.9379275889037832],
 [3.4383007204624936, 3.551119695656502, 5.884852621954787],
 [5.636376521209202, 6.898717433682599, 2.825141491184327],
 [8.109888775168502, 5.679589392945922, 8.018776433854713]]

In [7]:
type(nestedList)

list

In [8]:
myArray = np.array(nestedList)
myArray

array([[6.8054335 , 0.90325825, 1.93792759],
       [3.43830072, 3.5511197 , 5.88485262],
       [5.63637652, 6.89871743, 2.82514149],
       [8.10988878, 5.67958939, 8.01877643]])

**Important attributes of arrays**

In [9]:
print(myArray.ndim)  # Number of dimensions
print(myArray.shape) # Shape of the ndarray
print(myArray.dtype) # Data type contained in the array

2
(4, 3)
float64


#### Other functions to create arrays

**arange** - this is equivalent to the range function, except returns a one-dimensional array instead of a range object: 

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**ones**, **zeros**, **ones_like**, **zeros_like** - to create arrays filled with ones or zeroes with a given shape or with a shape similar to a given object:

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((4,3))

We can explicitly specify the data type with which an array should be created:

In [ ]:
newArray = np.array(nestedList, dtype = np.int)
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.float)
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.bool) # numbers >0 are True
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.unicode) # Unicode strings
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.object) # arbitrary objects
newArray

## Vectorized math

One of the most powerful and useful features of numpy, especially for data science, is the ability to vectorize mathmatical operations - that is to apply operations to each element of a vector or array simultaneously without needing to use a *for* loop

In [14]:
myArray

array([[6.8054335 , 0.90325825, 1.93792759],
       [3.43830072, 3.5511197 , 5.88485262],
       [5.63637652, 6.89871743, 2.82514149],
       [8.10988878, 5.67958939, 8.01877643]])

In [15]:
myArray + 3

array([[ 9.8054335 ,  3.90325825,  4.93792759],
       [ 6.43830072,  6.5511197 ,  8.88485262],
       [ 8.63637652,  9.89871743,  5.82514149],
       [11.10988878,  8.67958939, 11.01877643]])

In [16]:
myArray2 = np.array([[random.uniform(0, 3) for x in range(3)] for y in range(4)]) 
# creating a nested list and then a 2D array in one step
myArray2

array([[0.11180342, 0.98465866, 1.79449445],
       [1.73150373, 2.80483049, 2.50239923],
       [0.63915541, 2.45842594, 2.49571311],
       [2.1470421 , 2.71896573, 2.1623368 ]])

In [17]:
myArray + myArray2

array([[ 6.91723692,  1.88791691,  3.73242204],
       [ 5.16980445,  6.35595019,  8.38725185],
       [ 6.27553193,  9.35714337,  5.3208546 ],
       [10.25693088,  8.39855513, 10.18111323]])

In [18]:
newArray = myArray.astype(np.int)
newArray

array([[6, 0, 1],
       [3, 3, 5],
       [5, 6, 2],
       [8, 5, 8]])

In [19]:
newArray * 3

array([[18,  0,  3],
       [ 9,  9, 15],
       [15, 18,  6],
       [24, 15, 24]])

In [20]:
newArray * [1,2,3] 
# Elementwise multiplication on rows
# That is, in each row, the first column is multiplied by 1, the second by 2 and the third by 3

array([[ 6,  0,  3],
       [ 3,  6, 15],
       [ 5, 12,  6],
       [ 8, 10, 24]])

In [21]:
newArray * [[1], [2], [3], [4]] # Elementwise multiplication on columns

array([[ 6,  0,  1],
       [ 6,  6, 10],
       [15, 18,  6],
       [32, 20, 32]])

These types of numpy operations make it very easy and efficient to work with matrices and perform matrix algebra

In [22]:
np.sqrt(newArray)

array([[2.44948974, 0.        , 1.        ],
       [1.73205081, 1.73205081, 2.23606798],
       [2.23606798, 2.44948974, 1.41421356],
       [2.82842712, 2.23606798, 2.82842712]])

In [23]:
np.log(newArray + 1) # to avoid a log(0) error

array([[1.94591015, 0.        , 0.69314718],
       [1.38629436, 1.38629436, 1.79175947],
       [1.79175947, 1.94591015, 1.09861229],
       [2.19722458, 1.79175947, 2.19722458]])

These vectorized functions return an array of the appropriate shape - the same shape as the input array in the examples above.

There are also operations that are applied to an array which return a scalar value, usually the result of some type of aggregation

In [24]:
np.sum(newArray)

52

In [25]:
np.max(newArray)

8

In [26]:
np.mean(newArray)

4.333333333333333

#### What we have looked at here is just a small fraction of the operations and functionality available with numpy arrays - we have only looked at some of the features that are most relevant for us.

## Pandas

In [27]:
import pandas as pd

<b>From Wikipedia:

Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license. The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.</b>

<a href = "https://en.wikipedia.org/wiki/Pandas_(software)">Full article here</a>

**Pandas** is built on top of *NumPy* and has the following features:
<ul>
<li>Data structures with labeled axes</li>
<li>Arithmetic Operations and reductions</li>
<li>Integrated time series functionality</li>
<li>Handling of Missing data</li>
<li>Merge, sorting, filtering and other functionlities</li>
</ul>

*Pandas* has two main data structures - *Series* and *DataFrame*

## Series

In [28]:
from pandas import Series, DataFrame # this is actually optional; see below

In [29]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [30]:
a[1:]

[2, 3, 4]

In [31]:
obj = Series([3,6,9,12])

# I can use the method Series because I imported it explicitly from pandas in the previous step
# If I do not import Series explicitly, I need to use the syntax pandas.Series or pd.Series

In [32]:
obj

0     3
1     6
2     9
3    12
dtype: int64

In [33]:
type(obj)

pandas.core.series.Series

In [34]:
obj.values # just the values

array([ 3,  6,  9, 12])

In [35]:
obj.index # just the indices

RangeIndex(start=0, stop=4, step=1)

In [36]:
# casualty counts in WW2
ww2_cas = Series([8.7e6,4.3e6,3.0e6,2.1e6,4e5],index=['USSR','Germany','China','Japan','USA'])
ww2_cas

USSR       8700000.0
Germany    4300000.0
China      3000000.0
Japan      2100000.0
USA         400000.0
dtype: float64

In [37]:
ww2_cas.values

array([8700000., 4300000., 3000000., 2100000.,  400000.])

In [38]:
ww2_cas.index

Index(['USSR', 'Germany', 'China', 'Japan', 'USA'], dtype='object')

In [39]:
ww2_cas['USA']

400000.0

In [40]:
ww2_cas > 4e6

USSR        True
Germany     True
China      False
Japan      False
USA        False
dtype: bool

In [41]:
sum(ww2_cas > 4e6)

2

In [42]:
ww2_cas[ww2_cas > 4e6] # check which countries had casualties > 4 million

USSR       8700000.0
Germany    4300000.0
dtype: float64

In [43]:
'USSR' in ww2_cas

True

In [44]:
'France' in ww2_cas

False

In [45]:
ww2_dict = ww2_cas.to_dict() # convert series into a dictionary
ww2_dict

{'China': 3000000.0,
 'Germany': 4300000.0,
 'Japan': 2100000.0,
 'USA': 400000.0,
 'USSR': 8700000.0}

In [46]:
ww2_series = Series(ww2_dict) # convert dictionary into a series
ww2_series

China      3000000.0
Germany    4300000.0
Japan      2100000.0
USA         400000.0
USSR       8700000.0
dtype: float64

In [48]:
countries = ['China','Germany','Japan','USA','USSR','Argentina'] # a list

In [49]:
ww2_dict

{'China': 3000000.0,
 'Germany': 4300000.0,
 'Japan': 2100000.0,
 'USA': 400000.0,
 'USSR': 8700000.0}

In [50]:
obj2 = Series(ww2_dict,index = countries) # passing indices from a list
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
dtype: float64

In [51]:
pd.isnull(obj2) # check for null values

China        False
Germany      False
Japan        False
USA          False
USSR         False
Argentina     True
dtype: bool

In [52]:
pd.notnull(obj2) # check for non-null values

China         True
Germany       True
Japan         True
USA           True
USSR          True
Argentina    False
dtype: bool

# Data frames

In [ ]:
#import webbrowser

In [ ]:
#website = 'https://en.wikipedia.org/wiki/NFL_win%E2%80%93loss_records'

In [ ]:
#webbrowser.open(website) # opens the webpage in browser

<a href = "https://en.wikipedia.org/wiki/NFL_win%E2%80%93loss_records">Click here </a>

Copy the first few lines (including header) from the table on the webpage

In [53]:
#nfl_frame = pd.read_clipboard()
nfl_frame = pd.read_csv('data/nfl_frame.csv')

In [54]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  
0               1960   NFC East  
1               1921  NFC North  
2               1920  NFC North  
3               1966   AFC East  
4               1960   AFC East  
5               1961  NFC North  
6               1996  AFC North  
7               1925   NFC East  
8               1960   AFC West  
9               1950   NFC West  
10              1933  AFC North  
11              1960   AFC West

In [55]:
type(nfl_frame)

pandas.core.frame.DataFrame

In [56]:
nfl_frame.columns

Index(['Unnamed: 0', 'Rank', 'Team', 'GP', 'Won', 'Lost', 'Tied', 'Pct.',
       'First NFL Season', 'Division'],
      dtype='object')

In [57]:
nfl_frame.shape

(12, 10)

In [58]:
nfl_frame.Lost

0     374
1     562
2     579
3     351
4     386
5     390
6     161
7     585
8     404
9     460
10    538
11    411
Name: Lost, dtype: int64

In [59]:
nfl_frame.First NFL Season # In R:nfl_frame$Rank
# this won't work for column names with spaces

SyntaxError: invalid syntax (<ipython-input-59-a29c00d3d266>, line 1)

In [60]:
nfl_frame.Total Games

SyntaxError: invalid syntax (<ipython-input-60-4844a6b143aa>, line 1)

In [61]:
nfl_frame['First NFL Season']

0     1960
1     1921
2     1920
3     1966
4     1960
5     1961
6     1996
7     1925
8     1960
9     1950
10    1933
11    1960
Name: First NFL Season, dtype: int64

In [62]:
nfl_frame[nfl_frame.Won > 500]

Unnamed: 0  Rank                 Team     GP  Won  Lost  Tied   Pct.  \
0            0     1       Dallas Cowboys    882  502   374     6  0.573   
1            1     2    Green Bay Packers  1,336  737   562    37  0.565   
2            2     3        Chicago Bears  1,370  749   579    42  0.562   
7            7     8      New York Giants  1,305  687   585    33  0.539   
9            9    10  San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11  Pittsburgh Steelers  1,179  614   538    20  0.532   

    First NFL Season   Division  
0               1960   NFC East  
1               1921  NFC North  
2               1920  NFC North  
7               1925   NFC East  
9               1950   NFC West  
10              1933  AFC North

In [63]:
nfl_frame[(nfl_frame.Won > 500) & (nfl_frame.Lost < 500)]

Unnamed: 0  Rank                 Team     GP  Won  Lost  Tied   Pct.  \
0           0     1       Dallas Cowboys    882  502   374     6  0.573   
9           9    10  San Francisco 49ers  1,002  528   460    14  0.534   

   First NFL Season  Division  
0              1960  NFC East  
9              1950  NFC West

In [64]:
nfl_frame[(nfl_frame.Won > 500) | (nfl_frame.Lost < 500)]

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  
0               1960   NFC East  
1               1921  NFC North  
2               1920  NFC North  
3               1966   AFC East  
4               1960   AFC East  
5               1961  NFC North  
6               1996  AFC North  
7               1925   NFC East  
8               1960   AFC West  
9               1950   NFC West  
10              1933  AFC North  
11              1960   AFC West

In [65]:
my_new_df = DataFrame(nfl_frame,columns=['Team','First NFL Season','Total Games'])

In [66]:
my_new_df

Team  First NFL Season  Total Games
0            Dallas Cowboys              1960          NaN
1         Green Bay Packers              1921          NaN
2             Chicago Bears              1920          NaN
3            Miami Dolphins              1966          NaN
4   New England Patriots[b]              1960          NaN
5         Minnesota Vikings              1961          NaN
6          Baltimore Ravens              1996          NaN
7           New York Giants              1925          NaN
8            Denver Broncos              1960          NaN
9       San Francisco 49ers              1950          NaN
10      Pittsburgh Steelers              1933          NaN
11          Oakland Raiders              1960          NaN

In [67]:
DataFrame(nfl_frame,columns=['Team','First NFL Season','Total Games','Stadium'])

Team  First NFL Season  Total Games  Stadium
0            Dallas Cowboys              1960          NaN      NaN
1         Green Bay Packers              1921          NaN      NaN
2             Chicago Bears              1920          NaN      NaN
3            Miami Dolphins              1966          NaN      NaN
4   New England Patriots[b]              1960          NaN      NaN
5         Minnesota Vikings              1961          NaN      NaN
6          Baltimore Ravens              1996          NaN      NaN
7           New York Giants              1925          NaN      NaN
8            Denver Broncos              1960          NaN      NaN
9       San Francisco 49ers              1950          NaN      NaN
10      Pittsburgh Steelers              1933          NaN      NaN
11          Oakland Raiders              1960          NaN      NaN

If column doesn't exist, creates a column with that name and fills with null values

In [68]:
nfl_frame.head() # head; default first 5 rows

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0           0     1           Dallas Cowboys    882  502   374     6  0.573   
1           1     2        Green Bay Packers  1,336  737   562    37  0.565   
2           2     3            Chicago Bears  1,370  749   579    42  0.562   
3           3     4           Miami Dolphins    800  445   351     4  0.559   
4           4     5  New England Patriots[b]    884  489   386     9  0.558   

   First NFL Season   Division  
0              1960   NFC East  
1              1921  NFC North  
2              1920  NFC North  
3              1966   AFC East  
4              1960   AFC East

In [69]:
nfl_frame.head(3)

Unnamed: 0  Rank               Team     GP  Won  Lost  Tied   Pct.  \
0           0     1     Dallas Cowboys    882  502   374     6  0.573   
1           1     2  Green Bay Packers  1,336  737   562    37  0.565   
2           2     3      Chicago Bears  1,370  749   579    42  0.562   

   First NFL Season   Division  
0              1960   NFC East  
1              1921  NFC North  
2              1920  NFC North

In [70]:
nfl_frame.tail()

Unnamed: 0  Rank                 Team     GP  Won  Lost  Tied   Pct.  \
7            7     8      New York Giants  1,305  687   585    33  0.539   
8            8     9       Denver Broncos    884  470   404    10  0.537   
9            9    10  San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11  Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12      Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  
7               1925   NFC East  
8               1960   AFC West  
9               1950   NFC West  
10              1933  AFC North  
11              1960   AFC West

In [71]:
nfl_frame.tail(2)

Unnamed: 0  Rank                 Team     GP  Won  Lost  Tied   Pct.  \
10          10    11  Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12      Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  
10              1933  AFC North  
11              1960   AFC West

In [72]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  
0               1960   NFC East  
1               1921  NFC North  
2               1920  NFC North  
3               1966   AFC East  
4               1960   AFC East  
5               1961  NFC North  
6               1996  AFC North  
7               1925   NFC East  
8               1960   AFC West  
9               1950   NFC West  
10              1933  AFC North  
11              1960   AFC West

In [73]:
nfl_frame['Stadium'] = "Levi's Stadium" # create a new column with the same value for all rows

In [74]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division         Stadium  
0               1960   NFC East  Levi's Stadium  
1               1921  NFC North  Levi's Stadium  
2               1920  NFC North  Levi's Stadium  
3               1966   AFC East  Levi's Stadium  
4               1960   AFC East  Levi's Stadium  
5               1961  NFC North  Levi's Stadium  
6               1996  AFC North  Levi's Stadium  
7               1925   NFC East  Levi's Stadium  
8               1960   AFC West  Levi's Stadium  
9               1950   NFC West  Levi's Stadium  
10              1933  AFC North  Levi's Stadium  
11              1960   AFC West  Levi's Stadium

In [75]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
nfl_frame['StadiumNumber'] = np.arange(nfl_frame.shape[0]) # create a new column with continuous numbering

In [77]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division         Stadium  StadiumNumber  
0               1960   NFC East  Levi's Stadium              0  
1               1921  NFC North  Levi's Stadium              1  
2               1920  NFC North  Levi's Stadium              2  
3               1966   AFC East  Levi's Stadium              3  
4               1960   AFC East  Levi's Stadium              4  
5               1961  NFC North  Levi's Stadium              5  
6               1996  AFC North  Levi's Stadium              6  
7               1925   NFC East  Levi's Stadium              7  
8               1960   AFC West  Levi's Stadium              8  
9               1950   NFC West  Levi's Stadium              9  
10              1933  AFC North  Levi's Stadium             10  
11              1960   AFC West  Levi's Stadium             11

In [78]:
nfl_frame['Total2'] = nfl_frame['Won'] + nfl_frame.Lost # create a new column by applying some calculations to existing columns

In [79]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division         Stadium  StadiumNumber  Total2  
0               1960   NFC East  Levi's Stadium              0     876  
1               1921  NFC North  Levi's Stadium              1    1299  
2               1920  NFC North  Levi's Stadium              2    1328  
3               1966   AFC East  Levi's Stadium              3     796  
4               1960   AFC East  Levi's Stadium              4     875  
5               1961  NFC North  Levi's Stadium              5     860  
6               1996  AFC North  Levi's Stadium              6     351  
7               1925   NFC East  Levi's Stadium              7    1272  
8               1960   AFC West  Levi's Stadium              8     874  
9               1950   NFC West  Levi's Stadium              9     988  
10              1933  AFC North  Levi's Stadium             10    1152  
11              1960   AFC West  Levi's Stadium             11     873

In [80]:
del nfl_frame['StadiumNumber']

In [81]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division         Stadium  Total2  
0               1960   NFC East  Levi's Stadium     876  
1               1921  NFC North  Levi's Stadium    1299  
2               1920  NFC North  Levi's Stadium    1328  
3               1966   AFC East  Levi's Stadium     796  
4               1960   AFC East  Levi's Stadium     875  
5               1961  NFC North  Levi's Stadium     860  
6               1996  AFC North  Levi's Stadium     351  
7               1925   NFC East  Levi's Stadium    1272  
8               1960   AFC West  Levi's Stadium     874  
9               1950   NFC West  Levi's Stadium     988  
10              1933  AFC North  Levi's Stadium    1152  
11              1960   AFC West  Levi's Stadium     873

In [82]:
del nfl_frame['Stadium']

In [83]:
nfl_frame

Unnamed: 0  Rank                     Team     GP  Won  Lost  Tied   Pct.  \
0            0     1           Dallas Cowboys    882  502   374     6  0.573   
1            1     2        Green Bay Packers  1,336  737   562    37  0.565   
2            2     3            Chicago Bears  1,370  749   579    42  0.562   
3            3     4           Miami Dolphins    800  445   351     4  0.559   
4            4     5  New England Patriots[b]    884  489   386     9  0.558   
5            5     6        Minnesota Vikings    870  470   390    10  0.546   
6            6     7         Baltimore Ravens    352  190   161     1  0.541   
7            7     8          New York Giants  1,305  687   585    33  0.539   
8            8     9           Denver Broncos    884  470   404    10  0.537   
9            9    10      San Francisco 49ers  1,002  528   460    14  0.534   
10          10    11      Pittsburgh Steelers  1,179  614   538    20  0.532   
11          11    12          Oakland Raiders    884  462   411    11  0.529   

    First NFL Season   Division  Total2  
0               1960   NFC East     876  
1               1921  NFC North    1299  
2               1920  NFC North    1328  
3               1966   AFC East     796  
4               1960   AFC East     875  
5               1961  NFC North     860  
6               1996  AFC North     351  
7               1925   NFC East    1272  
8               1960   AFC West     874  
9               1950   NFC West     988  
10              1933  AFC North    1152  
11              1960   AFC West     873

In [84]:
old_dict = {'SF':8.37e5,'LA':3.88e6,'NYC':8.4e6}
old_dict

{'LA': 3880000.0, 'NYC': 8400000.0, 'SF': 837000.0}

In [85]:
data_dict = {'City':['SF','LA','NYC'],'Population':[8.37e5,3.88e6,8.4e6]} # create a dictionary

In [86]:
data_dict

{'City': ['SF', 'LA', 'NYC'], 'Population': [837000.0, 3880000.0, 8400000.0]}

In [87]:
city_frame = DataFrame(data_dict) #create a data frame from a dictionary

In [88]:
city_frame

City  Population
0   SF    837000.0
1   LA   3880000.0
2  NYC   8400000.0

## End of part 3